name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-to-cloud-storage:
    name: Deploy to GCS Bucket
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
          with:
            node-version: 12.x
      - run: npm install
      - run: npm build

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}

      - name: Deploy to Bucket
        run: |-
          cd build
          gsutil -m rsync -R . ${{ secrets.GCS_BUCKET }}