name: Deploy PR Preview

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths-ignore:
      - '.docsearch/**'
      - 'README.md'
      - '.gitpod.yml'
  workflow_dispatch:

env:
  ALGOLIA_APP_ID: ${{secrets.ALGOLIA_APP_ID}}
  ALGOLIA_KEY: ${{secrets.ALGOLIA_KEY}}
  NO_INDEX: true

concurrency: preview-${{ github.ref }}

jobs:
  deploy-pr-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Cache NPM Packages
        uses: actions/cache@v4
        id: cache-npm-packages
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: Cache Build
        uses: actions/cache@v4
        id: cache-build
        with:
          path: |
            build
          key: ${{ runner.os }}-${{ github.sha }}

      - name: Set Preview Path
        run: echo "PREVIEW_PATH=sauce-docs/pr-preview/pr-${{ github.event.number }}" >> "$GITHUB_ENV"

      - name: Install Dependencies
        if: steps.cache-npm-packages.outputs.cache-hit != 'true' && github.event.action != 'closed' # Skip if the PR was closed
        run: |
          npm install

      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true' && github.event.action != 'closed' # Skip if the PR was closed
        run: |
          npm run build

      - name: Deploy PR
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
