name: End to End Cypress Tests
on: [push]
jobs:
  e2e-tests:
    # the example has Yarn workspace in its "root" folder
    # examples/start-and-yarn-workspaces
    # and tests in a subfolder like "workspace-1"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install

      - name: Cypress tests
        uses: ./
        with:
          build: yarn run build
          start: yarn run serve
          wait-on: 'http://localhost:3000'

      - name: Tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          spec: tests/**.test.js