name: End to End Cypress Tests
on: [push]
jobs:
  setup:
    # the example has Yarn workspace in its "root" folder
    # examples/start-and-yarn-workspaces
    # and tests in a subfolder like "workspace-1"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup
        uses: ./
        with:
          working-directory: ./
          build: yarn run build
          start: yarn start
          wait-on: 'http://localhost:3000'

      - name: Tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          spec: tests/**.test.js